### PR TITLE
Fix style support

### PR DESCRIPTION
**Pull request by dgeb**
SASS will be compiled if `src/ui/styles/app.scss` is present.

Otherwise, all CSS in `src/ui/styles` will be concat’d.

This is preliminary, but should be safe, and is compatible with
Module Unification. We’re not taking a stance on colocation (yet).

### CODE REVIEW

**Comment by topherfangio** [comment]
@dgeb By `colocation` do you mean having SCSS in other directories? Coming from the Angular world, it seems a bit odd to put your component styles in a shared file.

Seems pretty interesting though! I like how quick it is to get up-and-running and how speedy the livereload works!

**Comment by locks** [comment]
@topherfangio colocation means that the CSS will be alongside the component and template files:

```
src/ui/components/
└── hello-glimmer
    ├── component.ts
    ├── template.hbs
    └── style.css
```

We aren't taking a stance because we need to define the semantics ;)

**Comment by topherfangio** [comment]
Gotcha; yeah, that is exactly what I was asking. That certainly feels the most comfortable to me, but I'm open to a better solution if you come up with one :-)

**Comment by dgeb** [comment]
@topherfangio we will soon support any approach you want to take for styles via ember-cli addons, but for now we are providing a default approach that's embedded in the pipeline. 

I agree that it will be nice to co-locate styles. The question we're debating is whether by default we want to somehow scope those styles to the component with which they're co-located.

**Comment by chriseppstein** [comment]
> The question we're debating is whether by default we want to somehow scope those styles to the component with which they're co-located.

Yes, they should be scoped but this needs to be done well. @tomdale and I have been thinking about this 🤔

**Comment by webark** [comment]
@chriseppstein do you have more info on the approach that you where discussing? And what some of the pitfalls of the current approachs are?

**Comment by chriseppstein** [comment]
@webark some downsides:
1. an isolation solution like CSS-modules has very bad compression characteristics. The ident generation strategies generally introduce entropy and reduce the overall compressibility of CSS.
2. Highly isolated CSS tends to be more bloated because, well, it's isolated, which means that sharing styles is often done through repetition (Sass mixins for instance). This trades performance for developer convenience.
3. mechanisms for referering to other components' classes will necessarily require the need to resolve style conflicts without assuming a total ordering. The standard approach to this is to add specificity on the selector that needs to win. More specific selectors often increase coupling and decrease the runtime performance of an application.

i like the ergonomics of colocated and component oriented styles but I'd like to avoid the perf downsides. I'm working on an optimizing compiler for CSS components that constrains authoring flexibility of selectors, combined with template aware analysis, in exchange for being able to aggressively rewrite selectors so that a single style construct in the template is replaced by many shared selectors across the input components.

**Comment by webark** [comment]
agree entirely! have you checked out https://github.com/html-next/optimizing-css-compiler ? seems like it's along the lines of what your talking about.

**Comment by chriseppstein** [comment]
@webark I have. I work with Chris ;) so far we are taking different approaches independently but I'm meeting with him tomorrow to discuss aligning our efforts.

**Comment by webark** [comment]
@chriseppstein haha!! ok cool. For me, and this is just a personal "dream" as of right now, is that whatever solution shakes out, it ends up a composeable and modular solution. Sometimes it seems that many people have aligning goals, but different ideas on how to get there. I like the model of ember-cli-deploy for instance where rather then having "one solution to rule them all", there's a base that different aspects can be built upon. I feel that will enable greater collaboration if we can setup a system where you can opt into different packages to suit your individual tastes and needs, but still have a base and shared set of primitives and conventions to build off of. This way people aren't solving the base problems multiple times, and can focus on higher more far reaching solutions with more focus.

**Comment by chriseppstein** [comment]
Absolutely. Furthermore I don't see any reason why any of this should be ember/glimmer specific. That said it's not always clear what the boundaries of composition are until we have a few solutions and can refactor to a shared standard.

**Comment by webark** [comment]
@chriseppstein agreed! And it feels that we're getting there.. which is awesome!

**Comment by chriseppstein** [comment]
@webark I spoke with @runspired today and we hashed out some cool stuff. A lot of what he is thinking is very complimentary with what I'm working on.

**Pull request merged**
